services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.com/alist-org/alist-render.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5244
      - key: DB_TYPE
        value: mysql
        sync: true
      - key: DB_HOST
        value: www.db4free.net
        sync: true
      - key: DB_PORT
        value: 3306
        sync: true
      - key: DB_USER
        value: hd_alist
        sync: true
      - key: DB_PASS
        value: hd1991118
        sync: true
      - key: DB_NAME
        value: hd_alist
        sync: true
      - key: DB_TABLE_PREFIX
        value: alist_
        sync: true
      - key: CDN
        value: https://npm.elemecdn.com/alist-web@$version/dist
        sync: true
